### ISSUE TITLE
Release version of wasmer 0.18 which builds with modern compilers

### ISSUE THREAD

**Issue by matklad** [near/wasmer#103]
This dosen't really make sense, but it'll probably the easiest short-term fix for aurora to allow upgrade of their nearcore version without ripping out many of their tests

**Comment by matklad** [comment]
Ok, so I believe we can't *just* upgrade aurora and do need a new release here:

Aurora actually uses two versions of nearcore at the same time: 

https://github.com/aurora-is-near/near-sdk-rs/blob/ef4259bded4a62468068197464db7afef956b9b8/near-sdk-sim/Cargo.toml#L20

https://github.com/aurora-is-near/aurora-engine/blob/c579fc8f724176d053670f78214717d6769d3524/engine-tests/Cargo.toml#L40

One they use directly, another they pull from `near-sdk-sim`. `near-sdk-sim` is a bit of effectively dead code, and I don't think it makes sense to spend time upgrading that (and it uses nearcore somewhat extensively, so that upgrade isn't going to be trivial).

**Comment by nagisa** [comment]
As far as I can tell this is no longer a pain point.
